#Structure:
#bot_id:
# configuration:
#   date_YYYY_MM_DD:
#     - first change
#     - second change
# calibration:
#   date_YYYY_MM_DD:
#     - type1
#     - type2
# experiment:
#   date_YYYY_MM_DD:
#     - first experiment
#     - second experiment

autobot01:
  configuration:
    date_2019_05_30:
      - first setup of bot
    date_2019_05_31:
      - changed motor
  calibration:
    date_2019_05_30:
      - kinematics
      - camera intrinsics
      - camera extrinsics
  experiment:
    date_2019_05_30:
      - aido21_12345
      - aido2_67890123
    date_2019_05_31:
      - aido2_12345
      - aido2_67890
autobot02:
  configuration:
    date_2019_05_30:
      - first setup of bot
    date_2019_05_31:
      - changed led's
  calibration:
    date_2019_05_30:
      - kinematics
      - camera intrinsics
  experiment:
    date_2019_05_31:
      - aido2_1234567890
      - aido2_67890
autobot04:
  configuration:
    date_2019_05_30:
      - first setup of bot
    date_2019_05_31:
      - changed HUT
  calibration:
    date_2019_05_30:
      - camera intrinsics
      - camera extrinsics
  experiment:
    date_2019_05_31:
      - aido2_12345
